baseURL = "https://movies.tomhummel.com/"
languageCode = "en-us"
title = "Tom Hummel Movie Journal"

[taxonomies]
  tag = "tags"
  release_year = "release_years"

[params]
    Title = ""
    site_description = ""
    # twitter_handle = ""
    github_repo = "https://github.com/tphummel/movies"
    # facebook_handle =
    # instagram_handle =

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1