baseURL = "https://movies.tomhummel.com/"
languageCode = "en-us"
title = "Tom Hummel Movie Journal"

[taxonomies]
  tag = "tags"
  keyword = "keywords"
  collection = "collections"
  release_year = "release_years"
  cast_member = "cast_members"
  crew_member = "crew_members"
  genre = "genres"
  rating = "ratings"
  production_country = "production_countries"
  production_company = "production_companies"

[params]
    Title = ""
    site_description = ""
    # twitter_handle = ""
    github_repo = "https://github.com/tphummel/movies"
    # facebook_handle =
    # instagram_handle =

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1